name: ci 
on:
  push:
    branches:
      - master 
      - main
      - First-WIP
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material==9.1.8 mkdocs-glightbox
      - run: cd docs; mkdocs gh-deploy --force
